### PR TITLE
Support for Terraform 0.12 (fixes #55)

### LINKED ISSUE #55: Support for Terraform 0.12
Hello!

I tried using this module with Terraform 0.12 and I got errors due to the syntax change:

```
Error: Unsupported block type

  on .terraform/modules/bastion/main.tf line 6, in resource "aws_security_group" "bastion":
   6:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.


Error: Unsupported block type

  on .terraform/modules/bastion/main.tf line 51, in data "template_file" "user_data":
  51:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.
```

Apparently it's just a matter of adding the `=` sign ? (sorry, terraform noob here)

### PR DESCRIPTION
**Pull request by eliasdorneles**
Hello,

I tried upgrading the module to Terraform 0.12, the automated upgrade command `terraform 0.12upgrade`) does a good job.
I only had to solve manually one section (which had a comment explaining with the proper context).

I've also added a few lines to README pointing people to use the `v1.10.0` version if they're on Terraform 0.11.

Does this look good?

### CODE REVIEW

**Comment by eliasdorneles** [comment]
I had to update the type constraint for `extra_tags` as well.

Docs here:

- https://www.terraform.io/docs/configuration/types.html#structural-types
- https://www.terraform.io/upgrade-guides/0-12.html#type-constraints-on-variables

**Comment by Gazler** [comment]
I have tried this out and get the following error when I don't include an `eip` value:

 > Error: bastion: invalid tag attributes: value missing

If I make this change:

```diff
  tags = concat(
    [
      {
        "key"                 = "Name"
        "value"               = var.name
        "propagate_at_launch" = true
      },
-      {
-        "key"                 = "EIP"
-        "value"               = var.eip
-        "propagate_at_launch" = true
-      },
    ],
    var.extra_tags,
  )
```

Then it works.

Here's the plan with the missing value:

```diff
      + tags                      = [
          + {
              + "key"                 = "Name"
              + "propagate_at_launch" = "true"
              + "value"               = "bastion"
            },
          + {
              + "key"                 = "EIP"
              + "propagate_at_launch" = "true"
            },
        ]
```

**Comment by CarpathianUA** [comment]
I would like to this merged :)

**Comment by allan-simon** [comment]
@eliasdorneles ping :) , I think with @Gazler  modification it should be good ?

**Comment by eliasdorneles** [comment]
@allan-simon if i do that, then i'll break the behavior documented in the README:

> eip - EIP to put into EC2 tag (can be used with scripts like https://github.com/skymill/aws-ec2-assign-elastic-ip, default - empty value)

... because the `var.eip` wouldn't be used anywhere.

I dunno what's best to do here, tbh.

**Comment by antonbabenko** [comment]
[v2.0.0](https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys/releases/v2.0.0) of this module is Terraform 0.12 ready.

**Pull request merged**
